#!/bin/bash

# i3blocks mail module.
# Displays number of unread mail and an loading icon if updating.
# When clicked, brings up `neomutt`.

case $BLOCK_BUTTON in
    1) i3-msg 'exec ~/.local/bin/launcher-neomutt' > /dev/null ;;
    3) setsid mailsync >/dev/null & ;;
esac

new_mail="$(du -a ~/.local/share/mail/*/*/new/* 2>/dev/null | sed -n '$=')"

if [[ -z "$new_mail" ]]; then
    color="#3B4252"
else
    color="#BF616A"
fi
icon="<span font='Font Awesome'>&#xf003;</span>"

echo " <span color='$color'>$icon $new_mail</span>$(cat /tmp/imapsyncicon_$USER 2>/dev/null)"
